// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP-7JXwp-zBT68eLkRN-QYbGEB84dxqaQ',
    appId: '1:422069215753:web:52178021c4342860c9ced8',
    messagingSenderId: '422069215753',
    projectId: 'fatih-yigit',
    authDomain: 'fatih-yigit.firebaseapp.com',
    databaseURL: 'https://fatih-yigit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatih-yigit.appspot.com',
    measurementId: 'G-8XBDWL09M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuO5xcQXb031h7AlR77U1XDTFtbWRelBw',
    appId: '1:422069215753:android:fdc5d77d778f387fc9ced8',
    messagingSenderId: '422069215753',
    projectId: 'fatih-yigit',
    databaseURL: 'https://fatih-yigit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatih-yigit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYcPRSfEuHtdMBBhLqwjAQ8aXRE3HIV1Y',
    appId: '1:422069215753:ios:12333cb69ad34325c9ced8',
    messagingSenderId: '422069215753',
    projectId: 'fatih-yigit',
    databaseURL: 'https://fatih-yigit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatih-yigit.appspot.com',
    iosBundleId: 'com.example.shoppingNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYcPRSfEuHtdMBBhLqwjAQ8aXRE3HIV1Y',
    appId: '1:422069215753:ios:12333cb69ad34325c9ced8',
    messagingSenderId: '422069215753',
    projectId: 'fatih-yigit',
    databaseURL: 'https://fatih-yigit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fatih-yigit.appspot.com',
    iosBundleId: 'com.example.shoppingNotes',
  );

}